-- PART 1: Run as SYSDBA to nuke and recreate user
-- setup_part1.sql

ALTER SESSION SET "_ORACLE_SCRIPT"=true;

-- Kill any sessions using DSCAE
BEGIN
  FOR s IN (SELECT sid, serial# FROM v$session WHERE username = 'DSCAE') LOOP
    EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION ''' || s.sid || ',' || s.serial# || ''' IMMEDIATE';
  END LOOP;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Drop user  
DROP USER dscae CASCADE;

-- Recreate
CREATE USER dscae IDENTIFIED BY dscae123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE, CREATE SESSION TO dscae;
GRANT CREATE TABLE, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, CREATE VIEW, CREATE TYPE TO dscae;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO dscae;
GRANT EXECUTE ON SYS.UTL_I18N TO dscae;

PROMPT User DSCAE ready.
EXIT;
